/**
 * A ESTRADA DOS REIS e os anéis externos.
 *
 * A rede real é radial: cada senhorio tem uma estrada principal ligando a sua
 * sede ao Coração de Valdória. O anel externo cria rotas alternativas mais
 * lentas e perigosas — atravessar o centro quase sempre é mais rápido, mas nem
 * sempre é possível.
 */
import type { RoadDefinition } from "./types";

/** Estradas reais (main) — todas partem do Castelo Real. */
export const royalRoads: RoadDefinition[] = [
  {
    id: "road_reis_norte",
    name: "Estrada dos Reis — Ramal Norte",
    type: "main",
    regionId: "heart_of_valdoria",
    nodes: [
      "castelo_real",
      "posto_da_guarda",
      "bc_portao_de_pedra",
      "cruz_de_ferro",
      "fundicao_dravenor",
      "pedra_alta",
      "fortaleza_pedra_cinza",
    ],
    terrain: "hill",
    danger: 0.1,
    movementModifier: 1.1,
    windiness: 1.08,
  },
  {
    id: "road_reis_noroeste",
    name: "Estrada dos Reis — Ramal do Bosque",
    type: "main",
    regionId: "heart_of_valdoria",
    nodes: ["castelo_real", "cidade_alta", "bc_ponte_do_bosque", "serenvale", "castelo_verde"],
    terrain: "forest",
    danger: 0.1,
    movementModifier: 1.08,
    windiness: 1.12,
  },
  {
    id: "road_reis_leste",
    name: "Estrada dos Reis — Ramal das Marchas",
    type: "main",
    regionId: "heart_of_valdoria",
    nodes: ["castelo_real", "conselho_real", "bc_vau_de_karneth", "forte_avancado", "baradra", "castelo_karneth"],
    terrain: "plain",
    danger: 0.14,
    movementModifier: 1.05,
    windiness: 1.06,
  },
  {
    id: "road_reis_sudeste",
    name: "Estrada dos Reis — Via da Peregrinação",
    type: "main",
    regionId: "heart_of_valdoria",
    nodes: [
      "castelo_real",
      "capela_alaric",
      "bc_ponte_dos_peregrinos",
      "aguas_claras",
      "luminaria",
      "catedral_de_luminaria",
    ],
    terrain: "plain",
    danger: 0.07,
    movementModifier: 1.05,
    windiness: 1.08,
  },
  {
    id: "road_reis_sul",
    name: "Estrada dos Reis — Ramal do Mar",
    type: "main",
    regionId: "heart_of_valdoria",
    nodes: [
      "castelo_real",
      "granja_real",
      "bc_ponte_do_serpente",
      "mare_alta",
      "castelo_de_aurimar",
      "aurimar",
      "grande_porto",
    ],
    terrain: "plain",
    danger: 0.09,
    movementModifier: 1.05,
    windiness: 1.1,
  },
  {
    id: "road_reis_sudoeste",
    name: "Estrada dos Reis — Ramal dos Grãos",
    type: "main",
    regionId: "heart_of_valdoria",
    nodes: [
      "castelo_real",
      "mercado_da_coroa",
      "pouso_dos_mercadores",
      "bc_marco_dos_graos",
      "mercado_de_graos",
      "trigal",
      "castelo_de_campo_alto",
    ],
    terrain: "plain",
    danger: 0.07,
    movementModifier: 1,
    windiness: 1.05,
  },
];

/** Anel externo: ligações diretas entre senhorios vizinhos, sem passar pelo centro. */
export const ringRoads: RoadDefinition[] = [
  {
    id: "road_anel_elmwood_greystone",
    name: "Trilha das Faias",
    type: "trail",
    regionId: "elmwood",
    nodes: ["folhaterra", "bc_trilha_das_faias", "mina_negra"],
    terrain: "forest",
    danger: 0.3,
    movementModifier: 1.7,
    windiness: 1.35,
  },
  {
    id: "road_anel_greystone_karneth",
    name: "Passagem do Norte",
    type: "trail",
    regionId: "greystone",
    nodes: ["grande_pedreira", "bc_passagem_do_norte", "portao_rubro"],
    terrain: "mountain",
    danger: 0.42,
    movementModifier: 2.1,
    windiness: 1.45,
  },
  {
    id: "road_anel_karneth_vale",
    name: "Passo da Vigília",
    type: "secondary",
    regionId: "karneth",
    nodes: ["vigilia", "bc_passo_da_vigilia", "passo_da_fe"],
    terrain: "hill",
    danger: 0.3,
    movementModifier: 1.5,
    windiness: 1.2,
  },
  {
    id: "road_anel_vale_costa",
    name: "Caminho das Águas",
    type: "secondary",
    regionId: "sacred_vale",
    nodes: ["mosteiro_antigo", "bc_ponte_das_aguas", "baia_serena"],
    terrain: "hill",
    danger: 0.14,
    movementModifier: 1.3,
    windiness: 1.18,
  },
  {
    id: "road_anel_costa_campos",
    name: "Estrada Costeira",
    type: "main",
    regionId: "golden_coast",
    nodes: ["estaleiro_aurenna", "bc_estrada_costeira", "fazendas_centrais"],
    terrain: "coast",
    danger: 0.12,
    movementModifier: 1.1,
    windiness: 1.12,
  },
  {
    id: "road_anel_campos_elmwood",
    name: "Vau do Oeste",
    type: "secondary",
    regionId: "greenfields",
    nodes: ["haras_real", "bc_vau_do_oeste", "grande_serraria"],
    terrain: "river_crossing",
    danger: 0.2,
    movementModifier: 1.35,
    windiness: 1.2,
  },
];
